name: Maestro deployment

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: join(github.event.pull_request.labels.*.name) == 'pavel-test'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!


