name: Bump version
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      bump:
        description: 'Bump Type (choose value only if you did not choose an existing tag)'
        type: choice
        options:
        - patch
        - minor
        - major
    branches:
      - master
      - hotfix/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Extracting current maestro version
        run: |
          export PYTHONPATH=''
          python3 -c "from maestro import __version__ ; print(__version__)"

#      - uses: actions/checkout@v2
#      - name: Bump version and push tag
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v6.1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          default_bump: ${{ github.event.inputs.bump }}
#      - name: Create a GitHub release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.tag_version.outputs.new_tag }}
#          name: Release ${{ steps.tag_version.outputs.new_tag }}
#          body: ${{ steps.tag_version.outputs.changelog }}
#          release_branches: .*
#          fetch_all_tags: true
#      - name: get relevant tag
#        id: get-actual-tag
#        run: |
#          if [ -z "${{ steps.get-chosen-tag.outputs.tag }}" ] ; then
#            IMAGE_TAG=${{ steps.tag_version.outputs.new_tag }}
#          elif [ -z "${{ steps.tag_version.outputs.new_tag }}" ]; then
#            IMAGE_TAG=${{ steps.get-chosen-tag.outputs.tag }}
#          else
#            IMAGE_TAG=${{github.sha}}
#          fi
#          echo $IMAGE_TAG